package com.felixkroemer.common;

public enum ErrorCode {
  FILE_HANDLING_FAILED,
  FILE_MOVE_FAILED,
  STABILITY_CHECKS_EXCEEDED,
  NO_ANALYZER_AVAILABLE,
  ANALYSIS_INCOMPLETE,
  ANALYSIS_FAILED,
}
